# Generated by Django 3.0.2 on 2020-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=95)),
                ('message', models.TextField(max_length=350)),
            ],
        ),
    ]
